---

- name: restart influxdb
  service: name=influxdb state=restarted

- name: restart logstash
  service: name=logstash state=restarted

- name: restart nginx
  service: name=nginx state=restarted
  